name: Cypress Tests

# Controls when the action will run.
on: [push]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Install Dep
              run: npm install
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  build: npm run build
                  start: npm start
